### ISSUE TITLE
Fonts not rendering in New Workspace dialog in Linux

### ISSUE THREAD

**Issue by ajvincent** [buggins/dlangide#101]
![screenshot from 2016-01-20 23-45-26](https://cloud.githubusercontent.com/assets/1527783/12474596/39eb5d78-bfd1-11e5-93a0-e3c29ceff843.png)

**Comment by buggins** [comment]
Could you please attach logs of DlangUI starting (with list of fonts). It looks like wrong monotype font is selected

**Comment by ajvincent** [comment]
[dlangide-issue-101.txt](https://github.com/buggins/dlangide/files/98876/dlangide-issue-101.txt)

**Comment by buggins** [comment]
I hope it's fixed
Please confirm
