### ISSUE TITLE
Enter key by numpad doesn't work in source editing window

### ISSUE THREAD

**Issue by ajvincent** [buggins/dlangide#106]
The enter key above the shift key works fine, but the enter key on the numpad does nothing.

**Comment by ajvincent** [comment]
I notice other funky behavior using the numpad with num lock engaged...

**Comment by buggins** [comment]
What is platform?

**Comment by ajvincent** [comment]
Linux localhost.localdomain 4.3.3-300.fc23.x86_64 #1 SMP Tue Jan 5 23:31:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by buggins** [comment]
Fixed in DlangUI
