### ISSUE TITLE
"Cannot debug project:  Cannot find executable file" dialog in dlangide when running project

### ISSUE THREAD

**Issue by ajvincent** [buggins/dlangide#118]

**Comment by keywan-ghadami** [comment]
So the build faild to create the executible file. Can you provide any log/console messages?

**Comment by ajvincent** [comment]
2016-01-27 22:57:33.946 D  ExternalProcess.run dub ["build", "--build-mode=allAtOnce", "--build=unittest"]
2016-01-27 22:57:33.946 I  Trying to run program dub with args ["build", "--build-mode=allAtOnce", "--build=unittest"]
2016-01-27 22:57:34.048 I  Build completed successfully. Starting debug for project.

Running (in /home/ajvincent/d-language/dlangide/experimental/IntervalMap): dub build --build-mode=allAtOnce --build=unittest
Performing "unittest" build using dmd for x86_64.
intervalmap ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Builder finished with result 0

**Comment by keywan-ghadami** [comment]
I am wondering about the build options "unittest" instead of "debug", i guess someone with more experience will help soon.

**Comment by ajvincent** [comment]
--build=debug versus --build=unittest doesn't make any difference.

**Comment by keywan-ghadami** [comment]
Maybe it's something special in the project, are the example projects like tetris running fine? Can you please try --build="debug" and add --verbose to the build options maybe the executible is somewhere else as excpected.

**Comment by buggins** [comment]
What is your OS?
Run button starts debugging - will fail if GDB is not found (e.g. on Windows)

**Comment by buggins** [comment]
Try running w/o debug: Ctrl+F5

**Comment by ajvincent** [comment]
Linux localhost.localdomain 4.3.3-303.fc23.x86_64 #1 SMP Tue Jan 19 18:31:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Same results with Ctrl+F5.

I upgraded to DMD 2.070 yesterday... not sure if that matters.

**Comment by buggins** [comment]
Is it possible to attach logs?

**Comment by ajvincent** [comment]
[dlangide-118-log.txt](https://github.com/buggins/dlangide/files/109345/dlangide-118-log.txt)

The source code for the workspace in question is at https://github.com/ajvincent/d-experiments/tree/master/IntervalMap .

This might be worth noting:  dlangide builds the application correctly, and manually running the application from the command line works as expected.  It's probably the step in between, where dlangide looks up the application's executable, that's failing.  The log doesn't specify the command it's trying to execute to launch the application.

**Comment by ajvincent** [comment]
Confirmed:  By adding a line to dlangide/src/dlangide/ui/debuggerui.d:
        Log.i("Executable should be at " ~ executableFileName);
the generated output log said:
2016-01-28 23:17:14.416 I  Executable should be at /home/ajvincent/d-language/d-experiments/IntervalMap/bin/intervalmap

But, dub build wrote:
Copying target from /home/ajvincent/d-language/d-experiments/IntervalMap/.dub/build/application-debug-linux.posix-x86_64-dmd_2070-7BF3E40751C90DA46B095C760B85ED6B/IntervalMap to /home/ajvincent/d-language/d-experiments/IntervalMap/bin

...ED6B/IntervalMap != ...ED6B/intervalmap

This regression had to have happened in the last week, I think.

**Comment by keywan-ghadami** [comment]
I bet it's related to some setting in the dub file.
Am 29.01.2016 07:49 schrieb "Alexander J. Vincent" <notifications@github.com

**Comment by ajvincent** [comment]
https://github.com/ajvincent/d-experiments/blob/master/IntervalMap/dub.json

**Comment by ajvincent** [comment]
https://github.com/buggins/dlangide/blame/master/src/dlangide/workspace/project.d#L527-L528

**Comment by buggins** [comment]
do you have targetName specified in dub.json?

**Comment by buggins** [comment]
Is "targetName": "IntervalMap"

**Comment by buggins** [comment]
Could you please try recent version.
It should get targetName for executable name (if specified)

**Comment by ajvincent** [comment]
Blocked on https://github.com/buggins/dlangui/issues/170 - I cannot test right now.

**Comment by buggins** [comment]
Updated

**Comment by ajvincent** [comment]
Confirmed, the build is fixed :+1:
