### ISSUE TITLE
font customization

### ISSUE THREAD

**Issue by Extrawurst** [buggins/dlangide#12]
especially for the texteditor this would be needed badly. but a system to skin the whole UI (hinting for dark theme) would be even better

**Comment by keywan-ghadami** [comment]
Current state:
 the ide can switch the font by the theme settings but the font for the texteditor the font is still hardcoded. 

Whats left to do:
- We should make that text editor font also configurable. 
- We should make it also possible to select the sytem default font.

**Comment by buggins** [comment]
Implemented in v0.7.9
