### ISSUE TITLE
GUI freezes after multiple resize

### ISSUE THREAD

**Issue by zhaopuming** [buggins/dlangide#125]
When I drag resize the window for many times (I was trying to see the animation of resizing, which is a little laggy), the content pane would freeze from some time, that is when I want to click into the editor, it does not respond.

I am under Ubuntu, using dub build -b release.

I also noticed that even in the release mode, there are still a lot of debug logs, how can I turn it off?

**Comment by g4z3r** [comment]
* [Fixed, I think](https://github.com/buggins/dlangui/pull/169). I am not sure about all platforms.
* Well, I removed "registerFont" logs. `ForceLogs` option in the dlangui dub.json is active by default by some reason.

**Comment by buggins** [comment]
Can I close issue?

**Comment by zhaopuming** [comment]
Checked out the latest code and now the issue is gone. Thanks!
