### ISSUE TITLE
rdmd + readln

### ISSUE THREAD

**Issue by default0** [buggins/dlangide#131]
If you run d code containing a call to readln with rdmd it's impossible to terminate the execution, forcing you to restart dlangide if you want to launch your program again. Killing off the rdmd process externally causes dlangide to freeze.

**Comment by buggins** [comment]
Possible solution: run in external console - like it's done for Run w/o debug

**Comment by buggins** [comment]
Works ok under Windows

**Comment by buggins** [comment]
Checked on Linux - works ok in external console.

**Comment by buggins** [comment]
Closing
