### ISSUE TITLE
Code completion adds extra space

### ISSUE THREAD

**Issue by wyrex** [buggins/dlangide#146]
Ctrl-Space adds whitespace you have to delete afterwards before showing drop down. I think it would also be better if completion was shown automatically after '.' is typed. Happens on Windows 7.
![snipp](https://cloud.githubusercontent.com/assets/13369724/13831849/67237f2a-ebdf-11e5-89e1-1688b604cd25.PNG)

**Comment by buggins** [comment]
Fixed.
TODO: 
* show autocompletion after .
* Move popup below current line
* allow entering text - use to filter / shorten list
