### ISSUE TITLE
Pos1/home-key Behaviour

### ISSUE THREAD

**Issue by default0** [buggins/dlangide#148]
When hitting the home/pos1-key on the keyboard the cursor jumps to the start of the current line.
It would be much more convenient for the purposes of DlangIDE if the cursor jumped to the end of the indentation, if there is any indentation at the start of the current line.

Basically, currently in line:
```D
    int x = 5;
```
Cursor jumps to:
```D
|    int x = 5;
```
It would be much nicer if instead it jumped to:
```D
    |int x = 5;
```

**Comment by buggins** [comment]
Implemented in dlangui fix.
