### ISSUE TITLE
Linker error, due to std.experimental.allocator now being in phobos2.so

### ISSUE THREAD

**Issue by mleise** [buggins/dlangide#150]
When linking against the shared Phobos2 library, many programs which built on the external std.experimental.allocator (including DlangIDE) now fail to run when the runtime finds the module in both, the executable and Phobos.

```
Fatal Error while loading '/usr/lib64/libphobos2.so.0.71':
    The module 'std.experimental.allocator.common' is already defined in '.dub/packages/dlangide-0.5.72/bin/dlangide'.
```

**Comment by buggins** [comment]
not sure how to resolve this

**Comment by buggins** [comment]
I believe it's resolved after upgrading of DCD dependency version.
