### ISSUE TITLE
Empty window with location choice when creating new project

### ISSUE THREAD

**Issue by edwvee** [buggins/dlangide#151]
I'm using Windows 7 x64 and dmd 2.071.0. Built app with:
dub --build=release --arch=x86_64
and
dub --build=release

I went to main menu File->Create->New project, then i tried to change location. When i clicked on button with ..., i saw a small window with nothing in it. On x64 some time later app crashed.
https://yadi.sk/i/utUw-ChOrKBTd - here's a screenshot

**Comment by buggins** [comment]
Looks like issues with OpenGL context.

**Comment by buggins** [comment]
Fixed in v0.5.73
(don't forget to upgrade DlangUI)
