### ISSUE TITLE
Too fast double click and other

### ISSUE THREAD

**Issue by edwvee** [buggins/dlangide#152]
Windows 7x64 dmd 2.071.0
The latency between two clicks is too small if I want to get double click. It's really hard to achieve it every time i need it (for example when I'm choosing directory for project). Why no to take it from OS settings?
Next is not so important and is a matter of taste:
Why not to use default OS filesystem browsing window? I don't know if it possible. Anyway this is more comfortable.

**Comment by buggins** [comment]
Doubleclick time fixed in dlangui/#264

**Comment by buggins** [comment]
(for windows only now)
