### ISSUE TITLE
Build errors DMD v2.071.1-b2

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#153]
Hello. I've got the following build errors (Windows 7 x64, DMD v2.071.1-b2).
src\dlangide\ui\terminal.d(665,18): Error: function dlangide.ui.terminal.Termina
lDevice.close () is not callable using argument types (int)
src\dlangide\ui\terminal.d(677,24): Error: undefined identifier 'posix_openpt'
src\dlangide\ui\terminal.d(682,17): Error: undefined identifier 'grantpt'
src\dlangide\ui\terminal.d(682,44): Error: undefined identifier 'unlockpt'
src\dlangide\ui\terminal.d(684,22): Error: function dlangide.ui.terminal.Termina
lDevice.close () is not callable using argument types (int)
src\dlangide\ui\terminal.d(688,17): Error: undefined identifier 'ptsname'
src\dlangide\ui\terminal.d(691,22): Error: function dlangide.ui.terminal.Termina
lDevice.close () is not callable using argument types (int)
dmd failed with exit code 1.

**Comment by arietto** [comment]
DMD v2.071.0 also failed.

**Comment by buggins** [comment]
did you try to sync?
now should be ok

**Comment by arietto** [comment]
Thank you for quick fix. It works now.
