### ISSUE TITLE
Adding commit info in About Dialog

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#154]
Please, add git commit info in About Dialog

**Comment by buggins** [comment]
Do you know how to get this information? Any example?

**Comment by arietto** [comment]
I am a C++ programmer. I've used Mercurial and CMake.
CMake has module FindHg. https://cmake.org/cmake/help/v3.1/module/FindHg.html
Also it has FindGit module, but it does not contain useful macro (I mean analogue of HG_WC_INFO)
You can search unofficial macro GIT_WC_INFO on github, for example:
https://github.com/crodehacke/PISMcr/blob/92e779b698039e9b871c1d2e9a487ecf8e7bbc27/CMake/FindGit.cmake
So, the basic idea is to pass certain parameters to git process.

**Comment by benrob0329** [comment]
What about using something like http://code.dlang.org/packages/dlibgit for full Git integration?

**Comment by buggins** [comment]
So far, implemented workaround: using VERSION file from resources.
