### ISSUE TITLE
Combobox collapsing behaviour

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#157]
Combobox in settings window is not collapsed after the 2nd clicking on it.
This is not a default behaviour on Windows for native control. I think that it is more comfortable and intuitive to collapse it via clicking on it. I suppose that it requires dlangui combobox reconsidering.

**Comment by benrob0329** [comment]
It's not the default behavior on any platform that I have seen aside from TK/Motif.

**Comment by buggins** [comment]
Probably, it's closing and then reopening.
So, proper behavior - to close combobox list popup?

**Comment by arietto** [comment]
Hello, Vadim. Yes, you are right - "proper behaviour - to close combobox list popup"
I've seen that Qt combobox (which is not native, by the way) closes its expanded list after clicking on it. Comboboxes in VS 2015 settings have the same behaviour.

**Comment by buggins** [comment]
Ok. To be fixed in DlangUI  buggins/dlangui#419

**Comment by buggins** [comment]
fixed in DlangUI
