### ISSUE TITLE
Some remarks using dlangide on OSX

### ISSUE THREAD

**Issue by p0nce** [buggins/dlangide#164]
- ~~When starting it can be long (between 2 and 10s here)~~
- ~~When opening a DUB project the whole .dub directory is opened (and expanded)~~
- ~~When using Build Project, the size of fonts in the Workspace Explorer change~~ (not seen again)
- There seems to be no way to attach the debugger to a running executable
- ~~window is black while resizing~~ (#174)
- ~~For a simple executable project, the binary isn't found, but it's right there generated by DUB.~~ (#173)
- ~~If a project depends on sub-packages they are not shown in the Workspace Explorer~~

**Comment by buggins** [comment]
long start: could you try to move mouse over the window right after start? probably it's window update issue

**Comment by buggins** [comment]
attaching to running executable is not yet supported on all platforms

**Comment by buggins** [comment]
sub-packages support will be handled by #171

**Comment by p0nce** [comment]
> long start: could you try to move mouse over the window right after start? probably it's window update issue

Was a problem outside of dlangide, my Mac would pause for many things. Now it's down to always 2 sec in debug build.

**Comment by p0nce** [comment]
Closed because it's now separated in different issues.
