### ISSUE TITLE
Fails to compile on OSX

### ISSUE THREAD

**Issue by kingsleyh** [buggins/dlangide#17]
I cloned the git repo and ran:
dub run

and this happened:

2015-02-08 21:12:49.750 D  Creating default theme
2015-02-08 21:12:49.750 E  Cannot load SDL2 libraryderelict.util.exception.SharedLibLoadException@../../../.dub/packages/derelict-util-1.9.1/source/derelict/util/exception.d(35): Failed to load one or more shared libraries:
	/usr/local/lib/libSDL2.dylib - dlopen(/usr/local/lib/libSDL2.dylib, 2): image not found
	../Frameworks/SDL2.framework/SDL2 - dlopen(../Frameworks/SDL2.framework/SDL2, 2): image not found
	/Library/Frameworks/SDL2.framework/SDL2 - dlopen(/Library/Frameworks/SDL2.framework/SDL2, 2): image not found
	/System/Library/Frameworks/SDL2.framework/SDL2 - dlopen(/System/Library/Frameworks/SDL2.framework/SDL2, 2): image not found
----------------
5   dlangide                            0x000000010ac37e43 void derelict.util.sharedlib.SharedLib.load(immutable(char)[][]) + 503
6   dlangide                            0x000000010ac36fa0 void derelict.util.loader.SharedLibLoader.load(immutable(char)[][]) + 124
7   dlangide                            0x000000010ac36e8a void derelict.util.loader.SharedLibLoader.load(immutable(char)[]) + 278
8   dlangide                            0x000000010ac36cef void derelict.util.loader.SharedLibLoader.load() + 107
9   dlangide                            0x000000010abbe4b5 int dlangui.platforms.sdl.sdlapp.sdlmain(immutable(char)[][]) + 53
10  dlangide                            0x000000010abbe47a _Dmain + 1510
11  dlangide                            0x000000010ac4bf6c D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 40
12  dlangide                            0x000000010ac4beb1 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 45
13  dlangide                            0x000000010ac4bf11 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() + 45
14  dlangide                            0x000000010ac4beb1 void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) + 45
15  dlangide                            0x000000010ac4be2d _d_run_main + 433
16  dlangide                            0x000000010abbe736 main + 34
17  libdyld.dylib                       0x00007fff8baad5c9 start + 1
18  ???                                 0x0000000000000001 0x0 + 1
Error executing command run: Program exited with code 1

**Comment by buggins** [comment]
It looks like you need to install libsdl2 on your system

**Comment by kingsleyh** [comment]
I already have this one:
Electron:~ kings$ brew install sdl2
Warning: sdl2-2.0.3 already installed
Unless perhaps it does not include any dev headers

**Comment by kingsleyh** [comment]
I have these also:
Electron:~ kings$ cd /usr/local/lib/libSDL2
libSDL2-2.0.0.dylib  libSDL2.dylib        libSDL2main.a
libSDL2.a            libSDL2_test.a

**Comment by buggins** [comment]
Dev headers are not required - Derelict is used to load them.
Your build is successful. It crashed while running - when failed to find and load sdl dynamic library.
Derelict searches it in
/usr/local/lib/libSDL2.dylib
But on your host, it should be 
/usr/local/lib/libSDL2/libSDL2.dylib

Probably, it can be fixed by adding of additional search path to derelict-sdl

**Comment by buggins** [comment]
possible workaround
# sudo cp /usr/local/lib/libSDL2/libSDL2.dylib /usr/local/lib/libSDL2.dylib

**Comment by buggins** [comment]
I've created pull request and issue #37 in DerelictSDL2 to add this path.

**Comment by buggins** [comment]
My pool request is integrated into DerelictSDL2 v1.9.2
Must compile ok on your mac now.

**Comment by kingsleyh** [comment]
It does thanks :)

**Comment by schveiguy** [comment]
FYI, just trying this out, had the same issue. I think it should be mentioned in the README that you have to install it somehow.
