### ISSUE TITLE
Can't run DUB project (OS X)

### ISSUE THREAD

**Issue by p0nce** [buggins/dlangide#173]
dlangide thinks the executable is here: 

![capture d ecran 2016-08-29 a 00 19 39](https://cloud.githubusercontent.com/assets/1067485/18037203/8ecae236-6d7e-11e6-956a-be484c1ad2ba.png)

when it's in `/Users/ponce/Desktop/gfm/examples/simpleshader/simpleshader`

**Comment by buggins** [comment]
Is it OSX related?

**Comment by buggins** [comment]
Probably, something is wrong with project's output path detection.

**Comment by buggins** [comment]
currently, binary path is hardcoded to "bin"
Workaround: add "targetPath": "bin" to dub.json
Going to fix soon
