### ISSUE TITLE
Can't dub run install (linux)

### ISSUE THREAD

**Issue by floare** [buggins/dlangide#175]
Hello :)
I want to learn and code whereas I can't install the very IDE I desperately need to do so.

Was not lucky googling around and ended up using console/terminal to start laborious coding cycles.
Does anyone know what is failing, maybe ? Any remedy ?
:)
....
experimental_allocator 2.70.0-b1: target for configuration "library" is up to date.
emsi_containers 0.3.0: target for configuration "library" is up to date.
libdparse 0.6.0: target for configuration "library" is up to date.
dsymbol 0.1.2: target for configuration "library" is up to date.
msgpack-d 1.0.0-beta.3: target for configuration "library" is up to date.
dcd 0.8.0: target for configuration "library" is up to date.
derelict-util 2.0.6: target for configuration "library" is up to date.
derelict-ft 1.1.2: target for configuration "library" is up to date.
derelict-gl3 1.0.19: building configuration "library"...
derelict-sdl2 2.0.1: building configuration "library"...
dlangui 0.9.2: building configuration "default"...
dlangide 0.7.1+commit.1.g420812a: building configuration "default"...
/usr/bin/ld: ../../.dub/packages/dlangui-0.9.2/lib/libdlangui.a(dimage.zlib.o): référence au symbole non défini «deflate»
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
ldc2 failed with exit code 1.

**Comment by buggins** [comment]
Looks like zlib is not found. Not sure why.

**Comment by Dzenly** [comment]
I met the similar problem. I removed dub from my system (debian 8 testing), install dmd (from .deb package) and problem is gone.

**Comment by buggins** [comment]
Should be fixed now.
I've added Zlib as linker parameter.
Please reopen if not fixed.
