### ISSUE TITLE
Errors list

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#177]
After click at an error in the compiler log, list always jumps to the end, so I need again and again scroll back.

And after click, view of the code editor is scrolled to right side (left side is outside view):
![editor](https://cloud.githubusercontent.com/assets/1731751/19240769/118b7752-8f36-11e6-872b-ea1c85e3163a.png)
also as you can see, the horizontal slider is missed (but view is shifted)

P.S,. Also the cursor is not visible at left position.

**Comment by buggins** [comment]
Fixed. As well, after build error, first error position will be located.
