### ISSUE TITLE
Problems with Horizontal scrollbar 

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#180]
Problem 1. See video https://dl.dropboxusercontent.com/u/78963719/D/dlangide/scrollbar.mp4

Problem 2. 
![scrollbar](https://cloud.githubusercontent.com/assets/1731751/19242779/e643903a-8f3e-11e6-8f96-7a3b95246feb.png)

**Comment by buggins** [comment]
Fixed in dlangui.
Will be applied once new dlangui version will be set in dub.json
