### ISSUE TITLE
Slow menu

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#183]
When I move mouse over the menu, the menu items higlighted with small lag. It looks like all works slow.

P.S. Also will be good if menu items will be closed when clicked at menu again. For example, I pressed `File`, it will show items (`Create`, `Open project or workspace...`, `Open file`, etc). If I press at `File` again, items must be disappear. Same behaviour must be when clicked outside the window (when window losts focus).

**Comment by buggins** [comment]
I believe now now menu behaves fine.
Not sure about lag.
