### ISSUE TITLE
Adding donation link directly into IDE

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#186]
Vadim, what about adding donation link directly into your IDE in order to stimulate more donations? For example, this [donation link](https://www.paypal.com/ru/cgi-bin/webscr?cmd=_flow&SESSION=ETrm02UibpPnzIfc6Mx_rKd18IL8hPyYfugJXOspBKSHBCOzKr__xJ_wryi&dispatch=5885d80a13c0db1f8e263663d3faee8d333dc9aadeed3fe0b5b299d55fd35542) be presented as a top-level empty menu right to the Help menu.

**Comment by buggins** [comment]
Donation link added to home screen and to Help menu
