### ISSUE TITLE
Why don't you include an exe file with this download ? 

### ISSUE THREAD

**Issue by vinodvinu** [buggins/dlangide#190]
This is like ordering a tea in 5 star hotel. If we order a tea, they will serve hot water, tea bag, sugar and a spoon separately. And its our responsibility to make it as a tea.

**Comment by TETYYS** [comment]
because installing dmd+dub in windows is so easy it's almost as compiling in linux

**Comment by buggins** [comment]
Included precompiled binaries for v0.7.60

Will upload binaries when some important changes are made.
