### ISSUE TITLE
Failed to compile on Mac - Sierra

### ISSUE THREAD

**Issue by ranoano** [buggins/dlangide#191]

**Comment by ranoano** [comment]
Just downloaded latest D package and trying to compile it using dub.

Latest message, after following the recommended steps ( force-build, clean-cache ... ) is

../.dub/packages/dcd-0.9.0-alpha4/dcd/src/server/autocomplete.d(169,25): Error: template instance server.autocomplete.dotCompletion!(SortedRange!(const(TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a"))[], "a < b")) error instantiating
dmd failed with exit code 1.

**Comment by buggins** [comment]
Is it fixed?

**Comment by buggins** [comment]
Please reopen if still not fixed after DCD version upgrade.
(Don't forget to upgrade DMD/LDC version, too).
