### ISSUE TITLE
Unable to write curly brackets on editor window - OSX

### ISSUE THREAD

**Issue by njasm** [buggins/dlangide#193]
iMAC with Portuguese keyboard layout.
SHIFT+ALT+8 OR 9 does not work.

**Comment by mrtryhard** [comment]
Same issue for me on Windows (8.1). I tested, and it appears that anything that uses AltGr (Alt Right) can't be typed.

**Comment by buggins** [comment]
There is a code to avoid Text event on Alt+Letter key press (e.g. Alt+F should open File menu and should not insert F character into editor.
This code should be modified in some manner.

**Comment by buggins** [comment]
Probably fixed by dlangui #414 in dlangui v0.9.107

**Comment by buggins** [comment]
v0.7.61 - fixes issue at least on Win32+SDL
Root cause: GrAlt + key produced Ctrl+Alt+ character but text with Ctrl was filtered out by Editor widget fix to avoid printing character on Ctrl + Space, Ctrl + A..Z, etc.

**Comment by buggins** [comment]
I cannot verify this issue myself, but I hope my fix will work for Mac, too.
Please reopen if there is still an issue.

**Comment by njasm** [comment]
@buggins thanks for the fix. currently i'm very busy but i'll try to validate the fix on OSX in the next week or so.. I'll report back my findings..

**Comment by buggins** [comment]
Thank you!
