### ISSUE TITLE
Failed to create new workspace in a subfolder of the home folder.

### ISSUE THREAD

**Issue by leh103** [buggins/dlangide#202]
I have build this ide on Windows 10 and two versions of Linux, it looks very promising. However, I tried to open the helloworld project in a new workspace in a subdirectory of my home directory and the ide created the new workspace in my home directory "/home/larry" which is the default. I did use the ellipse button to point it to the subfolder I wanted the workspace created in "/home/larry/Working", but it did not create it there. Is this a bug or operator error.

**Comment by buggins** [comment]
reproduced on Win32 - DlangIDE tries to create workspace dir in /home instead of /home/user
