### ISSUE TITLE
Shortcuts are hardcoded?

### ISSUE THREAD

**Issue by XuTpuK** [buggins/dlangide#208]
I modified file `c:\Users\USER\AppData\Roaming\.dlangide\shortcuts.json`, but shortcuts still old.

**Comment by buggins** [comment]
let me check

**Comment by buggins** [comment]
Doesn't your USER name have non-ascii characters (e.g. cyrillic?)

**Comment by dmi7ry** [comment]
Same problem. User name uses only ascii.

**Comment by buggins** [comment]
fixed in v0.7.96
I would recommend to delete old ~/.dlangide/shortcuts.json file to get it populated with recent standard shortcuts.
