### ISSUE TITLE
What is actual dlangide version ?

### ISSUE THREAD

**Issue by Dzenly** [buggins/dlangide#210]
Right now installed dlangide (clong git repo + dub run) and in Help/About it shows 0.6.19 version.
Is it correct ?

**Comment by TETYYS** [comment]
no

**Comment by buggins** [comment]
Version is hardcoded somewhere in code.
Updated from time to time.
It makes sense to extract version from git label.

**Comment by buggins** [comment]
I've exteralized version to file views/VERSION
Going to update it before each tagging of release.
