### ISSUE TITLE
IDE hangs with malformed json file

### ISSUE THREAD

**Issue by taumuon** [buggins/dlangide#211]
Hi, I created a new workspace, and then I added a new entry to the json file, but I forgot the comma, i.e. I had
{
    "name": "laplace-fill",
    "targetName": "laplace-fill",
    "targetType": "executable",
    "targetPath": "bin"
    "dependencies": {
		"dlib": "~>0.11.0"
    }
}

the comma missing before the dependencies. On doing a build, the GUI hung, and had to be killed.

I couldn't then open the workspace in a new session - I found the problem building the project via dub in the command line, fixed the json file, then I was able to open the workspace. I'm running DLangIDE v0.6.19 on Windows 10.

**Comment by buggins** [comment]
Closing issue - assuming it's fixed by g4z3r changelist.
