### ISSUE TITLE
Access violation after failed compilation

### ISSUE THREAD

**Issue by TETYYS** [buggins/dlangide#216]
Sorry that's all I got before it crashed:

![dlangide_2017-06-06_22-38-26](https://user-images.githubusercontent.com/3091645/26848376-e54fdad6-4b08-11e7-8bfc-bf1f6b9c29be.png)

**Comment by buggins** [comment]
Is it still reproducible on recent version?

**Comment by buggins** [comment]
I hope it's fixed
