### ISSUE TITLE
Creating new file for vibe.d project

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#218]
Hello. It is impossible to create *.dt HTML templates for vibe.d within this IDE. DlangIDE contains only 3 templates: *.d, *.json and *.txt.

**Comment by buggins** [comment]
Work in progress...

**Comment by buggins** [comment]
Fix is implemented in v0.7.42 but not tested well.

**Comment by EmTee70** [comment]
When opening my vibe.d project, the `views` folder still is not shown in workspace.
How to add the folder?

Do you see a way to add syntax highlighting for other languages?
For example by using the same technique `less` is using?
