### ISSUE TITLE
tab key for indent does not work in editor

### ISSUE THREAD

**Issue by Extrawurst** [buggins/dlangide#22]
when marking multiple lines of code and pressing tab the code gets delted and a tab char inserted. the indent feature just works when the input focus is on the toolbar or by pressing the button in the toolbar

**Comment by buggins** [comment]
In my implementation, indent by Tab worked only when whole lines were selected.
Now checked how it works in visual studio and implemented similar behavior: when multiple lines selected - change indent, when selection is on single line - replace it with tab char.

**Comment by Extrawurst** [comment]
which commit? i would like to test ;)
