### ISSUE TITLE
Autocomplete failed

### ISSUE THREAD

**Issue by arietto** [buggins/dlangide#220]
Autocomplete (Ctrl space) failed for vibe.d project template. I mean no suggestion list after dot is triggered.
For example, `settings.port = 8080;`

**Comment by buggins** [comment]
Probably fixed under #203.

**Comment by buggins** [comment]
Please reopen if still reproducible.

**Comment by Gemorroj** [comment]
@buggins, reproduced for me.
no autocomplete for `vibe.d` project, but all fine with embedded examples.
---
dlangide v0.8.5, v0.8.10
windows 10 x64
