### ISSUE TITLE
build fails 

### ISSUE THREAD

**Issue by logicfish** [buggins/dlangide#226]
..\..\..\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\core\logger.d(109,23): Error: cannot implicitly
 convert expression & makeGlobal of type File function() nothrow @nogc @property ref @system to File*
..\..\..\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\core\logger.d(116,23): Error: cannot implicitly
 convert expression & makeGlobal of type File function() nothrow @nogc @property ref @system to File*
..\..\..\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\core\logger.d(123,37): Error: incompatible type
s for ((logFile) !is (& makeGlobal)): 'File*' and 'File function() nothrow @nogc @property ref @system'
..\..\..\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\core\logger.d(123,59): Error: incompatible type
s for ((logFile) !is (& makeGlobal)): 'File*' and 'File function() nothrow @nogc @property ref @system'
dmd failed with exit code 1.

**Comment by buggins** [comment]
Is it reproducible on recent version?

**Comment by logicfish** [comment]
it's not failing anymore.
