### ISSUE TITLE
Autocomplete's oddities [RU]

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#235]
Автозавершение показывает кучу странных опций. Например:
![autocomplete](https://user-images.githubusercontent.com/1731751/29238351-eba842b8-7f5d-11e7-850c-1186f7680db9.png)
в сравнении с Xamarin:
![autocomplete_xamarin](https://user-images.githubusercontent.com/1731751/29238372-4bb23d4e-7f5e-11e7-87c4-ae5d05ec912e.png)

Другой пример:
![autocomplete2](https://user-images.githubusercontent.com/1731751/29238376-55edeaec-7f5e-11e7-9cb2-09a4effb9cad.png)

И таких опций огромное количество.

Иногда dcd перестаёт работать. В этом случае при закрытии IDE слышно звук, как когда появляется системное окно с сообщением об ошибке (системный звук «Восклицание»), но самого окна не видно. Логи:
[dcd.log](https://github.com/buggins/dlangide/files/1219566/dcd.zip)
[ui.log](https://github.com/buggins/dlangide/files/1219563/ui.zip)

например, происходит при нажатии Ctrl+Space после `writeln(`

И последнее. Когда я использую автозавершение первый раз, происходит очень большая задержка между нажатием Ctrl+Space и появлением окна с вариантами (около 8 секунд ав простом проекте, который я тестировал). Как понимаю, в это время dcd  что-то анализирует/строит. Может быть возможно, чтобы это происходило в фоне при открытии проекта? Тогда при вызове автозавершения задержки уже не было бы.
Ах, ещё забыл. Если во время этой задержки нажать Ctrl+Space несколько раз, то окошек автозавершения появится несколько и после выбора варианта остальные окна не исчезнут.

**Comment by buggins** [comment]
Fixed double code completion results bug.
DCD requires some time (up to 10-20 seconds) to parse standard library.
Previously it was done on first DCD function invocation. Now it's done on project opening.
Delay before completion/goToDefinition now should be small if project is opened ~20 seconds or more ago.

**Comment by buggins** [comment]
Added simple completion results sorting and filtering.
Now it should be better.

**Comment by buggins** [comment]
Can I treat this issue as fixed or some improvements are still needed?

**Comment by dmi7ry** [comment]
По-прежнему есть проблемы.

Enums (пример со скриншота) работает нормально.
А второй пример со структурой (EObjects) теперь не работает совсем - при нажатии ничего визуально не происходит и DCD зависает (как описано в первом сообщении).

**Comment by buggins** [comment]
Reproduced crash in DCD - on 32 bit builds only.
Submitted issue and PR to dsymbol: https://github.com/dlang-community/dsymbol/issues/55

**Comment by dmi7ry** [comment]
Пробую самую последнюю версию - вроде зависания dcd исчезли.
Но странности остались.
Например, создал проект с derelict sdl2. Пишу строку:

    SDL_AddTimer(

Нажимаю ctrl+space, вставляется следующий текст:

    SDL_TimerID SDL_AddTimer(Uint32, SDL_TimerCallback, void*)

Если не ошибаюсь, это подсказка о типах функции, и должна выводиться где-то в виде подсказки (попап под редактируемой строкой, например).

**Comment by buggins** [comment]
fixed in v0.7.89
