### ISSUE TITLE
`Open` scrollbar bug

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#236]
see animation:

![scrollbar](https://user-images.githubusercontent.com/1731751/29239054-07fcad9a-7f6e-11e7-8034-aa8c173ea00b.gif)

**Comment by dmi7ry** [comment]
And one more bug with scrollbar's slider size:
![scrollbar_size](https://user-images.githubusercontent.com/1731751/29239203-118f8c24-7f73-11e7-8fc2-d1210c943a6d.gif)

(Preferences -> Editors -> Text Editors -> Font face)

**Comment by and3md** [comment]
This is dlangui `ScrollWidget` update problem, recently I found that if you add `VerticaLayout` with a lot of child widgets. Then if you scroll it down and remove some childs. `ScrollWidget` is not notified about this. 
PS: Is there any way to move issue to another project (dlangui)?
Or maybe we should make a copy in dlangui project.

**Comment by and3md** [comment]
I'll try to fix this in dlangui.

**Comment by dmi7ry** [comment]
@and3md No, it still doesn't work. But now there is no any visual reaction after pressing (see first animation - it changes color when pressed, but now it doesn't).

```
Dmitry@DMITRY-COMP f:\0\dlangide
$ dub run
Fetching dcd 0.9.1 (getting selected version)...
Fetching dlangui 0.9.93 (getting selected version)...
Performing "debug" build using dmd for x86.
emsi_containers 0.5.3: target for configuration "library" is up to date.
libdparse 0.7.1-beta.9: target for configuration "library" is up to date.
dsymbol 0.2.8: building configuration "library"...
msgpack-d 1.0.0-beta.6: target for configuration "library" is up to date.
dcd 0.9.1: building configuration "library"...
derelict-util 2.0.6: target for configuration "library" is up to date.
derelict-ft 1.1.3: target for configuration "library" is up to date.
derelict-gl3 1.0.23: target for configuration "library" is up to date.
derelict-sdl2 2.0.2: target for configuration "library" is up to date.
dlangui 0.9.93: building configuration "default"...
dlangide 0.7.46: building configuration "default"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Copying files for dlangui...
Copying files for dlangide...
Running .\bin\dlangide.exe
```

**Comment by and3md** [comment]
> No, it still doesn't work. But now there is no any visual reaction after pressing (see first animation - it > > changes color when pressed, but now it doesn't).

There was problem that pageUp shadow button was set to visible when position was value min sometimes (I found it on example 1 too) and that is fixed. Maybe there is another problem. I make more tests.

Preferences -> Editors -> Text Editors -> Font face is fixed for you in 0.9.93?

**Comment by and3md** [comment]
@dmi7ry  OK I found second bug in scrollbar. `layoutButtons()` makes first `_pageDown.layout(r);` and then set `_pageDown.visibility = Visibility.Visible;`. But in Widget.layout() is condition that returns before `_pos` change when visibility is `Gone` (this buttons some time has Visibility.Gone).

**Comment by and3md** [comment]
@buggins Maybe this condition should be removed? and if someone don't want `layout()` when widget has `Visibility.Gone` just check it before `layout()` call?

**Comment by dmi7ry** [comment]
> Preferences -> Editors -> Text Editors -> Font face is fixed for you in 0.9.93?

@and3md yes, this works correct.

**Comment by buggins** [comment]
I think we need to check if Widget.layout() is ever called for visibility==Gone before removing of check.

**Comment by and3md** [comment]
@dmi7ry Please upgrade dlangui to 0.9.94 in dub.json (then make `dub upgrade`), and test again.

**Comment by dmi7ry** [comment]
@and3md Yes, now works fine.

**Comment by buggins** [comment]
Updated dlangui dep. 
Can we close this defect?
