### ISSUE TITLE
Wrong name in "recent projects"

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#238]
I open project (dub.json) then do something. After IDE restart I see `.dlangidews` instead of project's name (path, etc)

![recent projects](https://user-images.githubusercontent.com/1731751/29239117-a1bfed74-7f6f-11e7-8f0b-c222b8ce259e.png)

**Comment by buggins** [comment]
could you please provide content of dub.json?

**Comment by dmi7ry** [comment]
```
{
 "name": "engine",
 "authors": [
     "Dmitry"
 ],
 "description": "KEngine",
 "copyright": "Copyright © 2017, Dmitry",
 "license": "proprietary",
    "dependencies": {
        "consoled": "~>1.0.4",
		"sdlang-d": "~>0.10.1"
    }
}
```

**Comment by buggins** [comment]
Reproduced.

**Comment by buggins** [comment]
fixed.
As well, added menu item Window/Show home screen.
