### ISSUE TITLE
GUI/Theme Issues

### ISSUE THREAD

**Issue by dmi7ry** [buggins/dlangide#240]
1. В тёмной теме крестик закрытия вкладки плохо виден (особенно в активной вкладке).
![tabs](https://user-images.githubusercontent.com/1731751/29239141-9566577e-7f70-11e7-9052-d102065ef2dd.png)

2. В treeview выделение выглядит в точности как нажатая кнопка (стандартная тема Windows 7 Aero). 
![treeview](https://user-images.githubusercontent.com/1731751/29239169-b4a126cc-7f71-11e7-85ef-3d13565f268d.png)
Хочется, чтобы выглядело как выделение. У меня в ОС по умолчанию выглядит так (активное окно/ не активное):
![treeview_win7](https://user-images.githubusercontent.com/1731751/29239429-cc36f134-7f78-11e7-80dd-4d09cfca437a.png) ![treeview_inactive_win7](https://user-images.githubusercontent.com/1731751/29239440-ec6c5b42-7f78-11e7-9af7-daa09ac2368e.png)

3. В treeview окна настроек выделение несимметрично - с правой стороны отступ значительно меньше. Конечно, на работоспособность не влияет, но неуютно :)
![treeview](https://user-images.githubusercontent.com/1731751/29239169-b4a126cc-7f71-11e7-85ef-3d13565f268d.png)

4. Не хватает возможности выбора шрифта _интерфейса_ IDE (шрифт + размер).

**Comment by buggins** [comment]
Fixed tree and menu items style (copy + paste from Eclipse)

**Comment by buggins** [comment]
Working on UI font settings.

**Comment by dmi7ry** [comment]
Ещё пара моментов. 

1. В тёмной теме чёрные треугольники плохо видны (на скрине выделено прямоугольником).
2. Можно ли уменьшить горизонтальный отступ между нодами? Между первыми двумя строками (engine и engine) отступ вполне нормальный, а вот все остальные - больше, из-за чего дерево получается слишком широким.

![dark_theme](https://user-images.githubusercontent.com/1731751/29740497-01ac9fc6-8a82-11e7-9f03-60a2edb535fc.png)

**Comment by buggins** [comment]
thanks, will try to improve it

**Comment by buggins** [comment]
Fixed all findings.
