### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ASHIT-AXAR** [buggins/dlangide#241]
hello friends.
i have a little problem on building dlangide:

D:\ashit\software\dcompiler\DlangUI\dlangide-master>dub run
Fetching dcd 0.9.1 (getting selected version)...
Fetching msgpack-d 1.0.0-beta.6 (getting selected version)...
Fetching emsi_containers 0.5.3 (getting selected version)...
Fetching dsymbol 0.2.8 (getting selected version)...
Fetching dlangui 0.9.50 (getting selected version)...
Fetching libdparse 0.7.1-beta.9 (getting selected version)...
Performing "debug" build using dmd for x86.
emsi_containers 0.5.3: building configuration "library"...
libdparse 0.7.1-beta.9: building configuration "library"...
C:\Users\axar\AppData\Roaming\dub\packages\libdparse-0.7.1-beta.9\libdparse\src\
dparse\lexer.d(1789,12): Error: module std.math import 'nextPow2' not found
dmd failed with exit code 1.

how can i fix this ?

**Comment by ZombineDev** [comment]
It seems your compiler is too old. You need to use a compiler at least at the level of DMD 2.071. I would recommend truing either the latest dmd or ldc.

**Comment by buggins** [comment]
Solution: upgrade compiler.
Closing defect.

**Comment by ASHIT-AXAR** [comment]
Hello again :)) 
today i was download new    "dmd-2.075.1.exe"   and installed. ( windows 7 )
i tried to recompile dlangide.  (dub run)
good news is,    that error is no more.
now i have more of them    :)))))

---------------------------------------------------------------------------------------
D:\ashit\software\dcompiler\DlangUI\dlangide-master>dub run
Performing "debug" build using dmd for x86.
emsi_containers 0.5.3: target for configuration "library" is up to date.
libdparse 0.7.1: building configuration "library"...
dsymbol 0.2.8: building configuration "library"...
msgpack-d 1.0.0-beta.6: target for configuration "library" is up to date.
dcd 0.9.1: building configuration "library"...
derelict-util 2.0.6: target for configuration "library" is up to date.
derelict-ft 1.1.3: target for configuration "library" is up to date.
derelict-gl3 1.0.23: target for configuration "library" is up to date.
derelict-sdl2 2.0.2: target for configuration "library" is up to date.
dlangui 0.9.50: building configuration "default"...
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\dm
l\parser.d(34,8): Deprecation: function std.utf.toUTF8 is deprecated - To be rem
oved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\dm
l\parser.d(34,8): Deprecation: function std.utf.toUTF8 is deprecated - To be rem
oved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\dm
l\tokenizer.d(7,8): Deprecation: function std.utf.toUTF8 is deprecated - To be r
emoved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\dm
l\tokenizer.d(7,8): Deprecation: function std.utf.toUTF8 is deprecated - To be r
emoved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\pa
ckage.d(86,12): Deprecation: function std.utf.toUTF8 is deprecated - To be remov
ed November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\pa
ckage.d(86,12): Deprecation: function std.utf.toUTF8 is deprecated - To be remov
ed November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\files.d(428,16): Deprecation: function std.utf.toUTF8 is deprecated - To be r
emoved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\files.d(428,16): Deprecation: function std.utf.toUTF8 is deprecated - To be r
emoved November 2017. Please use std.utf.encode instead.
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\logger.d(109,23): Error: cannot implicitly convert expression & makeGlobal of
 type File function() nothrow @nogc @property ref @system to File*
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\logger.d(116,23): Error: cannot implicitly convert expression & makeGlobal of
 type File function() nothrow @nogc @property ref @system to File*
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\logger.d(123,37): Error: incompatible types for ((logFile) !is (& makeGlobal)
): 'File*' and 'File function() nothrow @nogc @property ref @system'
C:\Users\axar\AppData\Roaming\dub\packages\dlangui-0.9.50\dlangui\src\dlangui\co
re\logger.d(123,59): Error: incompatible types for ((logFile) !is (& makeGlobal)
): 'File*' and 'File function() nothrow @nogc @property ref @system'
dmd failed with exit code 1.
---------------------------------------------------------------------------------------------


errors show depreacated, to be removed, nothrow, nogc ...
i am doing something wrong ??

**Comment by and3md** [comment]
I think you try compile too old dlangide version. Make `git pull` on your dlangide git repository then `dub upgrade`. Current dlangui version is 0.9.99 not 0.9.50.

**Comment by buggins** [comment]
Try 

`dub upgrade --force-remove`
