### ISSUE TITLE
What's the way of using existing projects?

### ISSUE THREAD

**Issue by russel** [buggins/dlangide#243]
I have a number of existing D projects using a mix of Dub, SCons, Meson, CMake for building. DlangIDE appears to want to insist on creating a new workspace with new projects in it. What is the official way of creating a DlangIDE project from an existing project?

**Comment by buggins** [comment]
DlangIDE supports only DUB projects.
You can open existing dub project (dub.json / dub.sdl) to import project into dlangide.

**Comment by EmTee70** [comment]
Please make this more clear in the documentation: 
"**You can open existing dub project (dub.json / dub.sdl) to import project into dlangide."**

**Comment by buggins** [comment]
Following section is added to README.md

Importing of existing project
=============================

DlangIDE supports only DUB project format.

To import existing DUB project, use menu item "File" / "Open project or workspace" and select dub.json or dub.sdl of your project to import.

**Comment by buggins** [comment]
Added this information on Wiki https://github.com/buggins/dlangide/wiki/Import-existing-project

It's available via menu `Help` /  `Online help`
