### ISSUE TITLE
File / New package.d creation

### ISSUE THREAD

**Issue by buggins** [buggins/dlangide#251]
Created as module.

**Comment by buggins** [comment]
Enhancement: add new template for package.

**Comment by kildin** [comment]
Теперь создается как пакет, но с лишней точкой на конце

**Comment by buggins** [comment]
Проверил - все нормально создается. Никаких точек.
Например, в директории tetris/src/tetris/core:
package tetris.core;

Возможно, ты создавал package прямо в корневой директории исходников (src).
Package должен лежать во вложенной директории.
Сейчас не даст создать такой package.

**Comment by kildin** [comment]
Показываю пошагово
1
![1](https://user-images.githubusercontent.com/31731315/30239941-4210e7dc-956f-11e7-9487-7cb564b1c745.jpg)
2
![2](https://user-images.githubusercontent.com/31731315/30239942-45b3c6ac-956f-11e7-8b82-db23a4e38c07.jpg)
3 Итого получается
![3](https://user-images.githubusercontent.com/31731315/30239944-50dabd06-956f-11e7-965a-f4cbbff19211.jpg)
Тогда как вроде должно быть на выходе получиться "module test"

![4](https://user-images.githubusercontent.com/31731315/30239950-86b0daa0-956f-11e7-8433-b3cadf38d504.jpg)

**Comment by buggins** [comment]
Fixed package module name creation.
File dialog now may be closed with Ctrl+Enter.
In New Folder dialog, editor is focused, and Enter key acts as Ok.
