### ISSUE TITLE
Can't "File->Create->New File" if there are no open modules [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#257]
Аналогично #256 если нет открытого модуля, не работает пункт главного меню New File / комбинация Ctrl+N. При этом в контекстном меню в Workspace Explorer пункт "New File" работает.

**Comment by kildin** [comment]
Команда создать файл доступна, при выделенном проекте (через контекстное и главное меню) и при выделенном workspace (только через главное меню), хотя очевидно что в этих двух контекстах операция не может быть выполнена. Очевидных решения два: или скрыть команду в недоступных режимах или сделать disabled.

![2](https://user-images.githubusercontent.com/31731315/30239788-4dcefb3e-956c-11e7-8593-63d49f4d672c.jpg)
![1](https://user-images.githubusercontent.com/31731315/30239789-4f1e8c98-956c-11e7-8072-036edf56a82c.jpg)

**Comment by buggins** [comment]
Should be fixed in v0.7.75
