### ISSUE TITLE
Default focus in Create new folder dialog [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#258]
По-умолчанию, при окрытии диалога "Create new folder" фокус установлен на кнопке "Ок", тогда как должен быть в EditLine.
Upd. И на клавишу Enter после ввода названия папки кнопка "Ок" не реагирует

**Comment by buggins** [comment]
Implemented.

**Comment by kildin** [comment]
В диалоге "New file" заработало, но речь шла о диалоге создания папки. Его бы тоже доделать.
![1](https://user-images.githubusercontent.com/31731315/30240028-e02f9048-9570-11e7-96a5-4e97352ee3a4.jpg)

**Comment by buggins** [comment]
Reopened to fix New Folder dialog as well.

**Comment by buggins** [comment]
Now it should be ok.

**Comment by buggins** [comment]
Should be fixed in v0.7.75
