### ISSUE TITLE
Win 7.1 x32. Crash on exit in minimal config. [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#261]
При сборке в конфигурации minimal, во время закрытия окна IDE происходит аварийный вылет.  Компилятор DMD 2.075.1. Скриншот версии 0.7.71, но ошибка была и в предыдущих релизах.
![crash_on_exit](https://user-images.githubusercontent.com/31731315/30222125-ce3815ec-94ce-11e7-86d1-b181e6e57506.jpg)

**Comment by buggins** [comment]
cannot reproduce

**Comment by kildin** [comment]
Попробую последний релиз погонять на x32 и x64 машинах, возможно это "x32 only"

**Comment by buggins** [comment]
я собирал на x64 машине но версия для x86

**Comment by buggins** [comment]
Please reopen if issue still reproducible

**Comment by kildin** [comment]
Баг стабильно воспроизводится на Win7 x32. На 64 битной системе воспроизвести пока не удалось, но есть заметный лаг при закрытии IDE. 
"Reopen" если я правильно понимаю можно делать только собственноручно закрытым "Issue"

**Comment by buggins** [comment]
я нашел проблему тормозов на закрытии 
войдет в следующую метку

**Comment by buggins** [comment]
в логах после падения ничего нет?

**Comment by kildin** [comment]
В логах Windows или программы ?

**Comment by kildin** [comment]
Вот лог программы после падения
[ui_log.pdf](https://github.com/buggins/dlangide/files/1300051/ui_log.pdf)

**Comment by buggins** [comment]
Можешь попробовать на 0.7.80 - не исправилось?

**Comment by kildin** [comment]
Да, проблема решена
