### ISSUE TITLE
Win 7.1 x32. The IDE is not working in a console configuration [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#262]
При запуске IDE, собранной в консольной конфигурации, показывается следующее окно и больше ничего не происходит:
![dlnag ide console](https://user-images.githubusercontent.com/31731315/30222328-83913518-94cf-11e7-9083-69e08469eb05.jpg)

**Comment by buggins** [comment]
попробуй размер окна поменять

**Comment by kildin** [comment]
После изменения отрисовывается, но нужно его каждый раз менять при старте, независимо от выставленного размера окна. Даже при стартовом 235x80.

**Comment by buggins** [comment]
Проблема с первым обновлением окна. Надо фиксить.

**Comment by buggins** [comment]
will be fixed once DlangUI v0.9.123 is used.
