### ISSUE TITLE
Workspace Explorer: Duplication of dependencies after Build project [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#268]
После сборки проекта дублируются зависимости в Workspace Explorer (Строчка X11)
После переоткрытия проекта дубли пропадают до следующей сборки.
![new](https://user-images.githubusercontent.com/31731315/30248701-91bc005c-9635-11e7-9c83-3a9c324e9010.jpg)

**Comment by kildin** [comment]
В продолжение...
![double](https://user-images.githubusercontent.com/31731315/30253197-01897812-9689-11e7-8fa1-eb5bf83ce545.jpg)

**Comment by buggins** [comment]
trying to reproduce
