### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by Jiyan123** [buggins/dlangide#269]
Hello,
i think these issues were not listed already:
text which has keywords in it marks these keywords sometimes, example:
size_t ind;

so the "in" in ind is getting marked!

then 3 "smaller" enhancement suggestion:
1: QuickOutline window from the code with all the functions, structs, classes etc.
2: as soon as { is written in the code there should automatically a } be inserted
3: visualtion of tabs and spaces should be possible to turn off

Btw amazing work your doing there! :)

**Comment by buggins** [comment]
3) Edit / Preferences / Text editors / uncheck Show white space

**Comment by buggins** [comment]
Reproduced issue with `in` highlight.
