### ISSUE TITLE
Hidden tabs in main window [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#281]
![tabs](https://user-images.githubusercontent.com/31731315/30341865-582c48f2-9800-11e7-91f1-9ade73d466c0.jpg)
Если открыть много закладок, не помещающиеся на экран закладки скрываются и к ним нет доступа. Возможно ли организовать:
1. Кнопки горизонтальной прокрутки для закладок. Например, как реализовано в Firefox (кнопки автоматически появляются при большом количестве закладок и скрываются когда все закладки помещаются в главном окне):
![tabscroll](https://user-images.githubusercontent.com/31731315/30342162-6d43fcca-9801-11e7-8f44-e384df6dd7c2.jpg)

2. Выпадающий список со списком всех открытых закладок, для быстрого переключения, появляющийся в случае если все закладки не помещаются на экране:
![tabsmenu](https://user-images.githubusercontent.com/31731315/30342248-dd6e9b7c-9801-11e7-887f-d74e7b3d910d.jpg)

**Comment by buggins** [comment]
сделал список всех табов по кнопке справа
