### ISSUE TITLE
Unused StatusLine [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#284]
Вроде widget в главном окне есть, но на практике не видно, чтобы он где-либо использовался.

**Comment by buggins** [comment]
есть идеи, что там показывать?

**Comment by kildin** [comment]
В классическом консольном и windows интерфейсах строки состояния использовались для: 
1. Вывода подсказок о назначении пунктов меню (как главного меню, так и контекстных, вызываемых правым кликом).
2. Вывода расширенных (относительно кратких всплывающих tooltip) подсказок относительно назначения контроллов: кнопок toolbar'a, элементов интерфейса форм и т.д.
3. Отображение дополнительной "статусной" информации: состояние нажатых Numlock / CapsLock, позиция курсора X:Y в редактируемом коде и т.д.
Сейчас в статус барах можно наблюдать и "кликабельные" элементы управления.

Я сейчас посмотрел, что выводят в статус бар NetBeans, InteliJ, Eclipse и Notepad++, пункт 3 используют все, пункт 1-2 использует только InteliJ, у прочих статус бар  получается больше место на экране занимает, чем несет какую-то содержательную часть.

Если делать реализацию пунктов 1-2, то контроллы UI  и пункты меню должны иметь соотвествующее свойство,  что-то вроде statusBarText. Я кстати, не смотрел, реализовано это в UI или нет.
