### ISSUE TITLE
Incorrect window caption in "Project settings" [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#286]
В заголовке окна "Project settings" выводится "dlangui settings"

**Comment by shiche** [comment]
No, this is dlangIde settings. I will translate it now.

**Comment by buggins** [comment]
BTW, new project and new file dialogs are not translated.
@shiche, do you want to take this task?

**Comment by shiche** [comment]
dlangui settings - correct, if dlangui project is current. First word is a name of project. Do you think about more clear solution?

**Comment by kildin** [comment]
Может быть сделать заголовок в формате:
Project settings: Current_project_name

**Comment by buggins** [comment]
@shiche исправил
v0.7.79 
вроде бы нормально
