### ISSUE TITLE
Toolbar: incorrect value of the "Build configurations" when reopening a project [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#295]
При переоткрытии проекта состояние "Build configurations" сбрасывается на "debug", но контролл продолжает отображать свое предыдущие состояние.
![debub_value](https://user-images.githubusercontent.com/31731315/30432393-33e6ed38-996a-11e7-998d-b3ded9a59e52.jpg)

**Comment by buggins** [comment]
may be fixed together with #277
