### ISSUE TITLE
Create .di file in "Create->New File" dialog [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#296]
D, кроме .d файлов, формально поддерживает файлы интерфейса .di
Средствами  IDE нет возможности создания таких файлов.

**Comment by buggins** [comment]
.di обычно создаются компилятором из .d когда строится библиотека.
Точно нужно ручное создание .di?

**Comment by kildin** [comment]
Не, знаю, сам не использовал. Исходил из описания языка, где формально они заявлены. Например, у Александриеску в книге .di фигурирует не раз (хотя конечно книга не новая):
> Модуль D – это текстовый файл с расширением .d или .di. Инструмен-
> тарий D не учитывает расширения файлов при обработке, но по общему 
> соглашению  в  файлах  с  расширением  .d  на ходится  код  реализации, 
> а в файлах с расширением .di (от D interface – интерфейс на D) – код ин-
> терфейсов.

**Comment by dmi7ry** [comment]
Нет, не нужны они. Если есть сомнения, то можно посмотреть в любых других редакторах - их там нет.

**Comment by buggins** [comment]
Ок. Закрываю.
