### ISSUE TITLE
Don't update "*" status in caption [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#298]
В заголовке окна не корректно обновляется символ "*":
1. При изменении модуля, чтобы символ появился в заголовке, для обновления заголовка в окне нужно переключиться между вкладками кода.
2. После сохранения изменений в модуле, в заголовке окна "*" не исчезает, для обновления заголовка необходимо опять же переключиться между вкладками кода.

**Comment by buggins** [comment]
странно, раньше работало

**Comment by buggins** [comment]
reproduced

**Comment by buggins** [comment]
поправил - сейчас в заголовке окна показывается имя workspace
