### ISSUE TITLE
Artifact scroll [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#313]
Трудноуловимый баг. Вылезает горизонтальная прокрутка справа от строки кода, кода проводишь справа от строки мышью и курсор находится не на строке. Вылезло первый раз на большой строке с длинной цепочкой вызовов, путем научного тыка удалось редуцировать воспроизводящийся баг до такого минимального размера. Строка должна быть с кириллицей, с латинскими буквами и цифрами воспроизвести не удалось. При замене второго параметра с перечисления на число или строку баг так же исчезает.
![scroll_bug](https://user-images.githubusercontent.com/31731315/30637208-5a06a7fc-9e00-11e7-87c4-1bba6dd74afe.jpg)

**Comment by buggins** [comment]
completion or docs popup?

**Comment by kildin** [comment]
Скролл сам по себе всплывает и ни к чему не относится. Предлагаю протестировать приведенный пример. Достаточно подвести и задержать на пару секунд курсор мыши в пустой области справа от конца строки test(). Скролл показывается справа от курсора мыши.

**Comment by buggins** [comment]
как раз подержать, не двигая мышкой - просмотр документации по методу
можно лог посмотреть
странно, при чем тут русские буквы. Возможно, положение курсора мыши в тексте для двухбайтных символов как-то не так определяется.

**Comment by kildin** [comment]
Вот еще типичный пример из кода
`Window sprWin = Platform.instance.createWindow("Справочник номенклатуры", pWin, WindowFlag.Resizable, 600, 600);`
Действует если задержать мышь за знаком окончания ";" 
Клавиаутрный курсор кстати может быть и на самой строке.

**Comment by kildin** [comment]
А вот уже баг на строке с одной латиницей и вылезает, только если остановить мышь на menuItemClick или MenuItem, вдругой части строки или за ней скролл не показывается
![scroll_bug2](https://user-images.githubusercontent.com/31731315/30715297-791bc00e-9f1e-11e7-9d6f-a33650a5e7bb.jpg)

**Comment by buggins** [comment]
Идея: это однострочная подсказка (doc comment), закрытая появившимся скроллбаром.

**Comment by buggins** [comment]
Надо попробовать увеличить размер для doc popup

**Comment by kildin** [comment]
Побежден, но не до конца. Для строк с киррилицей неправильное позиционирование.
![scroll_bug3](https://user-images.githubusercontent.com/31731315/30738484-ef6c4926-9f92-11e7-981b-b4913e315ded.jpg)

**Comment by kildin** [comment]
Симптомы те же. Когда задерживаешь курсор мыши за строкой.

**Comment by buggins** [comment]
а вот это интересно.
постараюсь починить
