### ISSUE TITLE
@ Lets it crash

### ISSUE THREAD

**Issue by Jiyan123** [buggins/dlangide#318]
Hey,
i really hope i didnt overlook an existing issue.

The program crashes when i try to write an "@", when i copy it from elsewhere
and use STRG V it doesnt crash.

**Comment by buggins** [comment]
Cannot reproduce. Any additional details?
OS, backend, keys used to input @
Checked on win32, @ is entered by shift+2

**Comment by Jiyan123** [comment]
xubuntu.
Used key AltGr+q on german keyboard.
It seems to be generally a problem with AltGr+anyKey.
The generally used symbols like "[]{}\" work, but when it try to produce a
"€" (AltGr+e) it crashes aswell.

**Comment by Jiyan123** [comment]
I think it might be a problem with key combinations aswell, because things like "toggle comment" dont work aswell .

**Comment by buggins** [comment]
Thank you! Will try to reproduce and fix.

**Comment by buggins** [comment]
Reproduced on Windows SDL backend, AltGr+e (german layout)

**Comment by buggins** [comment]
Please confirm if issue is fixed.

**Comment by Jiyan123** [comment]
It is fixed! Thank you :)
