### ISSUE TITLE
Workspace Explorer: expand all / collapse all shortcuts do not work

### ISSUE THREAD

**Issue by buggins** [buggins/dlangide#320]

**Comment by kildin** [comment]
Оно работает, но только на все дочерние узлы от текущего выделенного, а нужно чтобы от корневого узла.

**Comment by buggins** [comment]
Так и должно от текущего работать.
Если надо все раскрыть - выбери проект вместо вложенной папки.

**Comment by kildin** [comment]
Тогда я не понял суть Issue, что не работало?

**Comment by buggins** [comment]
горячие клавиши Ctrl/+ Ctrl/-
