### ISSUE TITLE
Distorted text when copy/paste [RU]

### ISSUE THREAD

**Issue by kildin** [buggins/dlangide#327]
Иногда при копи/пасте фрагментов появляются какие-то дополнительные символы
Оригинал
![copy1](https://user-images.githubusercontent.com/31731315/30822855-e39e90b6-a232-11e7-954c-cde445d3c7ab.jpg)
После вставки
![copy2](https://user-images.githubusercontent.com/31731315/30822863-eb7d49bc-a232-11e7-8d99-a3c3052d7be2.jpg)

Также бывает что после копирования строки у копии после знака завершения строки ";" добавляется 4 пробела.

**Comment by buggins** [comment]
reproduced - there are 0x0D characters inserted
