### ISSUE TITLE
Opening dub.json as a regular file ends with error and application hangs

### ISSUE THREAD

**Issue by chalucha** [buggins/dlangide#33]
If json file is openned with Ctrl+O, it ends with:
---------------------------
Error
---------------------------
object.Error@(0): Access Violation
----------------
0x0050ABEA in @property dlangui.core.editable.EditableContent dlangui.core.editable.EditableContent.syntaxHighlighter(dlangui.core.editable.SyntaxHighlighter) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\editable.d(506)
0x00479D85 in void dlangide.ui.dsourceedit.DSourceEdit.setHighlighter() at C:\Users\tcha\Documents\GitHub\dlangide\src\dlangide\ui\dsourceedit.d(79)
0x00479C15 in bool dlangide.ui.dsourceedit.DSourceEdit.load(immutable(char)[]) at C:\Users\tcha\Documents\GitHub\dlangide\src\dlangide\ui\dsourceedit.d(65)
0x0047AE24 in bool dlangide.ui.frame.IDEFrame.openSourceFile(immutable(char)[], dlangide.workspace.project.ProjectSourceFile, bool) at C:\Users\tcha\Documents\GitHub\dlangide\src\dlangide\ui\frame.d(154)
0x0047D247 in D8dlangide2ui5frame8IDEFrame12handleActionMFxC7dlangui4core6events6ActionZ12__dgliteral2MFC7dlangui7dialogs6dialog6DialogxC7dlangui4core6events6ActionZv at C:\Users\tcha\Documents\GitHub\dlangide\src\dlangide\ui\frame.d(533)
0x004E461D in D7dlangui4core7signals57__T6SignalTC7dlangui7dialogs6dialog19DialogResultHandlerZ6Signal6opCall337C6DDE1539647A75563AF9DBCE2E77 at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\signals.d(200)
0x004E4D91 in int dlangui.core.collections.Collection!(void delegate(dlangui.dialogs.dialog.Dialog, const(dlangui.core.events.Action)), false).Collection.opApply(int delegate(ref void delegate(dlangui.dialogs.dialog.Dialog, const(dlangui.core.events.Action)))) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\collections.d(158)
0x004E45F0 in void dlangui.core.signals.Signal!(dlangui.dialogs.dialog.DialogResultHandler).Signal.opCall(dlangui.dialogs.dialog.Dialog, const(dlangui.core.events.Action)) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\core\signals.d(201)
0x004E417C in void dlangui.dialogs.dialog.Dialog.close(const(dlangui.core.events.Action)) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\dialogs\dialog.d(164)
0x004F5860 in bool dlangui.dialogs.filedlg.FileDialog.handleAction(const(dlangui.core.events.Action)) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\dialogs\filedlg.d(304)
0x0053B9DA in bool dlangui.platforms.common.platform.Window.dispatchAction(const(dlangui.core.events.Action), dlangui.widgets.widget.Widget) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(724)
0x004E88AC in bool dlangui.widgets.widget.Widget.dispatchAction(const(dlangui.core.events.Action)) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\widgets\widget.d(997)
0x004E8940 in bool dlangui.widgets.widget.Widget.handleClick() at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\widgets\widget.d(1008)
0x004E8E3F in bool dlangui.widgets.widget.Widget.onMouseEvent(dlangui.core.events.MouseEvent) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\widgets\widget.d(1109)
0x0053B856 in bool dlangui.platforms.common.platform.Window.sendAndCheckOverride(dlangui.widgets.widget.Widget, dlangui.core.events.MouseEvent) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(695)
0x0053C133 in bool dlangui.platforms.common.platform.Window.dispatchMouseEvent(dlangui.core.events.MouseEvent) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(907)
0x005434DC in bool dlangui.platforms.windows.winapp.Win32Window.onMouse(uint, uint, short, short) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(640)
0x005441E0 in WndProc at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(1143)
0x76DC791C in CallNextHookEx
0x76DC7B7A in CallNextHookEx
0x76DC97F4 in GetMessageW
0x76DC9859 in DispatchMessageW
0x0052B765 in int dlangui.platforms.windows.winapp.Win32Platform.enterMessageLoop() at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(752)
0x0045C9BB in UIAppMain at C:\Users\tcha\Documents\GitHub\dlangide\src\dlangide.d(72)
0x005044FE in int dlangui.platforms.windows.winapp.myWinMain(void*, void*, char*, int) at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(1023)
0x004D29FC in DLANGUIWinMain at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\windows\winapp.d(865)
0x0045C892 in WinMain at C:\Users\tcha\Documents\GitHub\dlangide\..\..\..\AppData\Roaming\dub\packages\dlangui-master\src\dlangui\platforms\common\platform.d(1350)
0x005ADF42 in WinMainCRTStartup
0x74DA919F in BaseThreadInitThunk
0x770B0BBB in RtlInitializeExceptionChain
0x770B0B91 in RtlInitializeExceptionChain
---------------------------
OK   
---------------------------

After which application hangs and must be manually terminated.

dmd 2.066.1, dub 0.9.22, windows 8 x64

**Comment by buggins** [comment]
Fixed by dlangui change.
