### ISSUE TITLE
File --> Create --> New File (or Ctrl + N) does nothing

### ISSUE THREAD

**Issue by notna123** [buggins/dlangide#339]
- Windows 7 and 10
- https://github.com/buggins/dlangide/releases/download/v0.8.5/dlangide-v0_8_5-bin-win32_x86-magomi-v0_3_2.zip

**Comment by buggins** [comment]
Do you have workspace opened?

**Comment by notna123** [comment]
ok, sorry, my bad... I just wanted to open an empty/new (*.d) file and test a bit of code... and due to my understanding/assumption "create new file" should do just that (if no WS or the like is opened / active)...

sorry for the noice & feel free to close the bug

 

Gesendet: Montag, 02. Oktober 2017 um 14:25 Uhr
Von: "Vadim Lopatin" <notifications@github.com>
An: buggins/dlangide <dlangide@noreply.github.com>
Cc: notna123 <notna@ist-einmalig.de>, Author <author@noreply.github.com>
Betreff: Re: [buggins/dlangide] File --> Create --> New File (or Ctrl + N) does nothing (#339)


Do you have workspace opened?

**Comment by buggins** [comment]
Ok. So I think, under this issue, I can disable Create New File menu item if workspace is not opened.

**Comment by notna123** [comment]
or, if you are that keen to change/improve the "new file" stuff... IMO it would be better to allow to create a new  *.d file if one is not in a workspace / project context...

THANKS anyhow for this nice IDE. it's great to see what you can do with/in D...

 

Gesendet: Dienstag, 03. Oktober 2017 um 08:31 Uhr
Von: "Vadim Lopatin" <notifications@github.com>
An: buggins/dlangide <dlangide@noreply.github.com>
Cc: notna123 <notna@ist-einmalig.de>, Author <author@noreply.github.com>
Betreff: Re: [buggins/dlangide] File --> Create --> New File (or Ctrl + N) does nothing (#339)


Ok. So I think, under this issue, I can disable Create New File menu item if workspace is not opened.
