### ISSUE TITLE
Search feature is required.

### ISSUE THREAD

**Issue by Freakazo** [buggins/dlangide#35]
A basic feature for finding text in the page.

I would like to tackle this. Where shall I display the search box and where would I display the results?
I was thinking we could make the area where the output pane is tabbed. We can then place Other sections there as well similar to how other IDEs do it.

I will keep in mind more advanced search features as I implement it.

**Comment by buggins** [comment]
I believe it's ok to implement search as panel, e.g. below editor.
It could contain editline for text to search, buttons find next / find previous, close button.
Close button may hide panel (e.g. setting visibility to GONE)
Useful feature could be highlight of all found occurences in text as well as on vertical scrollbar.
Please let me know if you need some help.

**Comment by buggins** [comment]
Find/replace mode may include additional editline for Replace text, and buttons replace next / replace all.
