### ISSUE TITLE
Error: undefined identifier overrideScreenDPI

### ISSUE THREAD

**Issue by leotada** [buggins/dlangide#357]
Occurs this error with master and tag v0.8.8 when building.
DMD 2.077.0
Dub 1.6
Fedora Linux 27 64 bits
> src/dlangide/ui/frame.d(1638,13): Error: undefined identifier overrideScreenDPI
src/dlangide/ui/frame.d(1639,13): Error: undefined identifier overrideScreenDPI
src/dlangide/ui/settings.d(121,111): Deprecation: dlangui.core.settings.to is not visible from module settings
src/dlangide/ui/settings.d(121,122): Error: undefined identifier systemScreenDPI
FAIL .dub/build/default-debug-linux.posix-x86_64-dmd_2077-AFCA8A61136319C1743E269CE8D10439/ dlangide executable
dmd failed with exit code 1.

**Comment by buggins** [comment]
try dub upgrade --force-remove

**Comment by leotada** [comment]
Resolved, thanks.
