### ISSUE TITLE
Root package dlangide references unknown package dcd

### ISSUE THREAD

**Issue by ASHIT-AXAR** [buggins/dlangide#360]

**Comment by ASHIT-AXAR** [comment]
what steps did i miss ?

**Comment by ASHIT-AXAR** [comment]
or how can i download pre-compiled windows executable?

**Comment by kildin** [comment]
https://github.com/buggins/dlangide/releases/download/v0.8.5/dlangide-v0_8_5-bin-win32_x86-magomi-v0_3_2.zip

**Comment by kildin** [comment]
dub build -b=release

**Comment by ASHIT-AXAR** [comment]
thank you.
>dub build -b=release
it compiled.
