### ISSUE TITLE
Only a limited selection of fonts

### ISSUE THREAD

**Issue by takase1121** [buggins/dlangide#370]
In the IDE there's only a few fonts selectable for the editor.

**Comment by WrongBit** [comment]
I confirm this issue and cannot realise why this stupidity is implemented at all?? What reason you have to limit user in font selection? Dictatorship is not the best way to write software.
One more note: characters looks soooo ugly on Windows 7! Why so? I hope you're NOT using that clumsy libfreetype-6.dll?? Windows has its own font rendering system which is obviously way better than any FOSS cr@p. Please use native renderer on Windows and allow full font list. Say, I use "Source Code Pro", but even after I put it in `c:\Users\USER\AppData\Roaming\.dlangide\settings.json`, IDE ignored this setting and continue to use hell knows what.

**Comment by keywan-ghadami** [comment]
@WrongBit so would you be able to provide a fix?

**Comment by takase1121** [comment]
right now I already lost interest in D and don't need this software anymore.

However, by looking at the source code of [dlangUI](https://github.com/buggins/dlangui/blob/d942853bcd458f563ee3c855332ab58c1f1e5faa/src/dlangui/platforms/common/startup.d), and also [this](https://github.com/buggins/dlangui/blob/master/src/dlangui/platforms/windows/win32fonts.d), I found out that the UI falls back to GDI (Or at least it seems) if it can't load libfreetype. 

So... The solution is simple and obvious.
Delete the libfreetype dll.

The GDI fonts doesn't really look the best but it looks okay and all your selections are back.

@WrongBit A bit of GitHub search and issue is fixed. Speaking of stupidity. I think this is more of an ignorance thing though.
