### ISSUE TITLE
String literals containing backspace character breaks syntax highlighting.

### ISSUE THREAD

**Issue by Freakazo** [buggins/dlangide#40]
eg
```d
    _resultLog.appendText(to!dstring("No matches found.\n"));
}
else {
```

All text following \ is coloured the same as string literals.

**Comment by thewilsonator** [comment]
Are you upstream or downstream of the fix for #38?

**Comment by Freakazo** [comment]
Upstream of #38 fix.

**Comment by buggins** [comment]
Strange... Must be fixed. Let me check

**Comment by Freakazo** [comment]
I said backspace in the title but meant backslash, just for the record.
