### ISSUE TITLE
onThemeChanged does not override any function

### ISSUE THREAD

**Issue by thewilsonator** [buggins/dlangide#41]
6995a7dc468b59e72a4eaabefa2342b646c0e0f4 added 
override void onThemeChanged() {
	backgroundColor = style.customColor("edit_background");
}
to ui/dsourceedit.d
dub/dmd fails with

src/dlangide/ui/dsourceedit.d(47): Error: function dlangide.ui.dsourceedit.DSourceEdit.onThemeChanged does not override any function
FAIL .dub/build/application-debug-posix.osx-x86_64-dmd_2067-5A4BC60499757844E0638EE9CF579B0C/ dlangide executable
Error executing command build: dmd failed with exit code 1.

**Comment by Freakazo** [comment]
Did you do `dub upgrade`?

**Comment by thewilsonator** [comment]
Thanks that fixed it. Which dependency needed up grading? I ask because I have patches in top of Derelict.* for correctly finding libs and I'd rather not dub upgrade each time.

**Comment by Freakazo** [comment]
It typically is dlangui.
