### ISSUE TITLE
sharedLog = new NullLogger() 64bit build compile error with dlangui0.10.2+dmd2.103 under win10

### ISSUE THREAD

**Issue by LukyGuyLucky** [buggins/dlangide#429]
dlangide.d ,line 33
sharedLog = new NullLogger();//no sharedLog function match

failed to compile under dmd 2.103,commented out get passed.

Everything goes well excep main menu File->Save All desn't work after source file been modified.'Save' works.

**Comment by GrimMaple** [comment]
Is this in any way related? https://github.com/buggins/dlangide/pull/426

If that PR fixes things, I will be glad to just merge it.

**Comment by LukyGuyLucky** [comment]
Since my dmd version is 2103,I just did a second try to modify import std.experimental.logger to std.logger ,the compiler failed to build with the same complaint.Just commented sharedLog=new Nulllogger() in version(release) get passed.
