### ISSUE TITLE
 Building error [dlangui/core/textsource.d' which cannot be read]

### ISSUE THREAD

**Issue by VlasovRoman** [buggins/dlangide#53]
src/ddc/lexer/textsource.d(3): Error: module textsource is in file 'dlangui/core/textsource.d' which cannot be read

**Comment by buggins** [comment]
Old dlangui version
Try `dub upgrade --force-remove; dub build --force`

**Comment by buggins** [comment]
Could you please confirm that dub upgrade resolves your problem?

**Comment by VlasovRoman** [comment]
Yeap, it works
