### ISSUE TITLE
dub building failing 

### ISSUE THREAD

**Issue by jamadagni** [buggins/dlangide#55]
Hello. While I don't think this is a bug in DLangIDE per se (since the error message seems to refer to another library), I'm not sure where else to go for help so here is the console output of my trying to do `dub run` and then again later `dub upgrade --force-remove && dub build --force`:

    Building dlib ~master configuration "library", build type debug.
    Running dmd...
    ../../../../../../../home/samjnaa/.dub/packages/dlib-master/dlib/math/sse.d(184): Error: bad type/size of operands 'mov'
    FAIL ../../../../../../../home/samjnaa/.dub/packages/dlib-master/.dub/build/library-debug-linux.posix-x86_64-dmd_2067-EB731D61241842D3EFF384ED3451EE8C/ dlib staticLibrary
    Error executing command build:
    dmd failed with exit code 1.

Please guide me as to how I can have an up and running version of DLangIDE. Is the problem caused by the latest versions of any of the various dependencies being buggy? I don't mind not having the latest versions (in fact, it was `dub` which installed them, not me) so long as I can get DLangIDE to work.

I'm using dmd 2.067.1 on Kubuntu Trusty 64 bit.

Thank you.

**Comment by Freakazo** [comment]
I'm on my mobile at the moment so I can't test it myself. But can you try
to use an older version of dlib? IIRC you can change the version to use
based on a version number tag in the dlib repository.

**Comment by jamadagni** [comment]
I'm inexperienced with dub. Can you guide me how to tell dub to use a specific version of dlib? As I said, I didn't install dlib at all -- it was entirely dub which did it.

**Comment by GanMatt** [comment]
It's a problem with dlib.

How do you make dub use an older version of dlib? I can't find the place to put the version number.

**Comment by Freakazo** [comment]
Can you guys clone https://github.com/buggins/dlangui, and see if it builds. If it gives the same issue try and replace all instances of `"dlib": "~master"` with `"dlib": "~>0.6.1"`.

**Comment by jamadagni** [comment]
Hello. I am not sure how to build dlangui separately. The [Wiki page there](https://github.com/buggins/dlangui/wiki/Getting-Started) only shows how to build it with an app. And dub.json inside dlangide dir doesn't have any dlib entry. Only dub.selections.json has such an entry, and I modified that and it now works.
