### ISSUE TITLE
latest DlangIde doesn't open on OSX due to libdparse error

### ISSUE THREAD

**Issue by kingsleyh** [buggins/dlangide#56]
Running dmd...
../../../.dub/packages/libdparse-master/src/std/d/parser.d(7): Error: module mallocator is in file 'std/experimental/allocator/mallocator.d' which cannot be read
import path[0] = ../../../.dub/packages/libdparse-master/src
import path[1] = /usr/share/dmd/src/phobos
import path[2] = /usr/share/dmd/src/druntime/import
FAIL ../../../.dub/packages/libdparse-master/.dub/build/library-debug-posix.osx-x86_64-dmd_2067-B24A89B02726B8E0BEA699F4AF413711/ dparse staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by buggins** [comment]
Isn't it fixed already?

**Comment by buggins** [comment]
Fixed in v0.3.18. Probably you need to execute `dub upgrade --force-remove` before building.
