### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by ZHANITEST** [buggins/dlangide#65]
Hi! :)

Original text is "// 블로그 타입 확인".

![sublime](https://cloud.githubusercontent.com/assets/6543940/11686233/85c1cc1c-9ec2-11e5-83f4-93a98402cb87.png)![dlang](https://cloud.githubusercontent.com/assets/6543940/11686250/9834d4e8-9ec2-11e5-8d84-2eab8cc44606.png)

(Left: sublime text 2 - 블로그 타입 확인, Right: dlangide -  똔끜ꗸ 타입 확인)

Some words were looks like wrong. Is dlangide support CJK?
Ooh, case by SublimeText2 encoded UTF-8.

Regards,

**Comment by buggins** [comment]
According to D standards, D source code should be in one of unicode formats (utf-8, utf-16, utf-32)
I think I can close this issue

**Comment by ZHANITEST** [comment]
Thx for your answer. Same utf-8 encoded file, same font(i guess Consolas), but breaking only DlangIDE. So strange problem...
Anyway... ok, if you want a closing, do it. :/

**Comment by buggins** [comment]
Could you try to save file as utf-32 and then try it in DlangIDE? Doesn't it give better result? If so, something is wrong with utf8 decoding

**Comment by keywan-ghadami** [comment]
i can reproduce this with an utf8 encoded file, but with utf32 encoded file everything is fine.
I will try to have a look at the utf8 decoding today

**Comment by keywan-ghadami** [comment]
fixed in dlangui see https://github.com/buggins/dlangui/pull/138

**Comment by buggins** [comment]
thank you for the fix
