### ISSUE TITLE
Nitpick: Code layout

### ISSUE THREAD

**Issue by default0** [buggins/dlangide#83]
Lots of code in DlangIDE uses spaces and tabs in a single file.
Should we use spaces/tabs everywhere and document this for contributors or leave it as it is?

![](http://puu.sh/m4IIH/ca96b607ca.png)

**Comment by buggins** [comment]
Going to create coding style docs.

**Comment by buggins** [comment]
Tabs replaced with spaces in all source files.
Added coding style document.

**Comment by sigod** [comment]
> Tabs replaced with spaces in all source files.

@buggins, http://habrahabr.ru/post/118208/

**Comment by buggins** [comment]
I just don't like tabs.
