### ISSUE TITLE
Names not showing in file dialogs

### ISSUE THREAD

**Issue by Esperantisto** [buggins/dlangide#87]
The names of files and folders are not showing in file dialogs (see screenshot). This is on Ubuntu 15.10 64 bit.

![screenshot from 2015-12-31 09-56-50](https://cloud.githubusercontent.com/assets/16503728/12066999/e49e8d52-afa6-11e5-9e1f-47cd28b8a063.png)

**Comment by keywan-ghadami** [comment]
Do you have some special theme settings? Maybe it's only a problem with the color. How does it look like if you select an other folder then "..".

**Comment by buggins** [comment]
Some issue with colors

**Comment by Esperantisto** [comment]
It's the built-in dark theme. Anyway, I tried on another PC, also with Ubuntu 15.10, and it works fine.

**Comment by buggins** [comment]
Do you see text when light theme is selected?

**Comment by itrombley** [comment]
I deleted the .dlangide and .dub folders, re-cloned the project, built and ran it and I still get the same issue.

![screenshot from 2016-01-04 12-25-08](https://cloud.githubusercontent.com/assets/14115714/12099715/130a2558-b2df-11e5-9199-ca32f8b124af.png)

**Comment by itrombley** [comment]
Here's the relevant output:
> 2016-01-04 12:32:07.791 D  FileDialog.openDirectory(/home/ivan4258/Dev/External/dlangide)
> 2016-01-04 12:32:07.794 D  Loading image from file @embedded@/folder.png
> 2016-01-04 12:32:07.794 D  Loading image from file @embedded@/project-d.png
> 2016-01-04 12:32:07.795 D  Creating SDL window
> 2016-01-04 12:32:07.797 I  Trying to create OpenGL 3.2 context
> 2016-01-04 12:32:07.798 I  Trying to create OpenGL 3.2 context
> 2016-01-04 12:32:07.864 I  Created successfully
> 2016-01-04 12:32:07.864 I  OpenGL is enabled
> 2016-01-04 12:32:07.864 D  SDLWindow.show()
> 2016-01-04 12:32:08.006 D  Loading image from file @embedded@/user-home.png
> 2016-01-04 12:32:08.010 D  Loading image from file @embedded@/dialog-cancel.png
> 2016-01-04 12:32:08.012 D  updateTexture for image cache page - setting image 1024x1024 tx=2
> 2016-01-04 12:32:09.044 D  updateTexture for image cache page - setting image 1024x1024 tx=2
> 2016-01-04 12:32:14.144 D  Destroying SDL window

**Comment by Esperantisto** [comment]
Here is the default theme. I also deleted the .dlangide and .dub folders and re-cloned the dlangide repository.

![screenshot from 2016-01-04 12-50-31](https://cloud.githubusercontent.com/assets/16503728/12100133/d618f4c8-b2e1-11e5-8482-1914acb070b0.png)

**Comment by keywan-ghadami** [comment]
@buggins this looks interesting: some information are there (the dot of dub.json file, the two dots directory, and size and date of dub.json file)  do you have some ideas what the cause could be?. @Esperantisto if you have some time please make some test for me because i like to help to fix that but i can not reproduce this. 1. What happens if you select the dub.file (the last entry in the dialog) is te filname completely displayed in the textbox at the bottom of that dialog. 2. Can you open the idelang project then by pressing open? 3.  And did you find similar effects somewhere else?

**Comment by buggins** [comment]
Probably some strange font is selected, which contains no english letters.

**Comment by Esperantisto** [comment]
I re-installed Ubuntu 15.10 and it works now.

**Comment by buggins** [comment]
Possible good fix could be implementing of fallback fonts support in DlangUI (fonts to get glyphs missing in other fonts)

**Comment by ajvincent** [comment]
Fedora 23, I see squares for each letter in the file picker's grid.

**Comment by buggins** [comment]
I hope it's fixed

**Comment by buggins** [comment]
Please confirm
