### ISSUE TITLE
Get Autocompletions crash

### ISSUE THREAD

**Issue by wyrex** [buggins/dlangide#89]
I don't know how it's supposed to work but each time I click Get Autocompletions from menu or Ctrl-Shift-G dlangide crashes with this error on Win 10 and v0.5.24.

![ernesti](https://cloud.githubusercontent.com/assets/13369724/12197501/293d472c-b610-11e5-94d8-7356a99193c0.PNG)

Other separate thing is when you select ldc from project settings and try 64 bit build, it gives this error (dmd build works as it should):

```
Running (in E:\Koodaus\Dlang\LaginenPaskaTest\NytLagaa\LagaaNiinVitusti): dub build --arch=x86_64 --compiler=ldc2 --build-mode=allAtOnce --build=debug
WARNING: DUB package names should always be lower case. Please modify the "name" field in E:\Koodaus\Dlang\LaginenPaskaTest\NytLagaa\LagaaNiinVitusti\dub.json accordingly.
WARNING: A deprecated branch based version specification is used for the dependency dlangui. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using ldc2 for x86_64.
derelict-util 2.0.4: target for configuration "library" is up to date.
derelict-ft 1.0.2: building configuration "library"...
ldc2: for the -march option: may only occur zero or one times!
ldc2 failed with exit code 1.
Builder finished with result 2
```

**Comment by buggins** [comment]
Reproduced

**Comment by buggins** [comment]
Crashes while trying to log warning using std.experimental.logger
				warning("Could not resolve location of module '", importPath, "'");
Logger not initialized?

**Comment by buggins** [comment]
Fixed by changing of stderr logger to file logger under windows.

**Comment by buggins** [comment]
Although, code completion and go-to-definition does not work for me (on windows).

**Comment by keywan-ghadami** [comment]
@wyrex the other build error was related to dub and fixed see https://github.com/D-Programming-Language/dub/commit/2d1df295b396e2b7a000ab5f82afde8177a3a841
