### ISSUE TITLE
Saving file changes line ends.

### ISSUE THREAD

**Issue by Freakazo** [buggins/dlangide#9]
After editing a file and saving it and then opening it with another editor such as vim all the content is on one line and where line ends should be the characters  *^M* is printed.

I'm on Arch Linux.

**Comment by buggins** [comment]
It's some bug. On opening of file, line ending style is being detected, and used when saving.
It looks like something is wrong in this implementation.
Let me check.

**Comment by buggins** [comment]
Fixed in dlangui v0.4.37
